### ISSUE TITLE
NoClassDefFoundError: org/codehaus/plexus/util/StringUtils on mvnd 1.0.0-m1 / Maven 4.0.0-alpha-3

### ISSUE THREAD

**Issue by ppalaga** [mojohaus/keytool#57]
Trying first builds with mvnd 1.0.0-m1 that is using Maven 4.0.0-alpha-3 and getting this error:

```
[INFO] --- keytool:1.6:generateKeyPair (generate-cxfca-keypair) @ camel-quarkus-integration-test-cxf-soap-ws-security-server ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.565 s (Wall Clock)
[INFO] Finished at: 2022-12-21T21:20:34+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:keytool-maven-plugin:1.6:generateKeyPair (generate-cxfca-keypair) on project camel-quarkus-integration-test-cxf-soap-ws-security-server: Execution generate-cxfca-keypair of goal org.codehaus.mojo:keytool-maven-plugin:1.6:generateKeyPair failed: A required class was missing while executing org.codehaus.mojo:keytool-maven-plugin:1.6:generateKeyPair: org/codehaus/plexus/util/StringUtils
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.codehaus.mojo:keytool-maven-plugin:1.6
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/data/m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.6/keytool-maven-plugin-1.6.jar
[ERROR] urls[1] = file:/home/data/m2/repository/org/codehaus/mojo/keytool-api/1.6/keytool-api-1.6.jar
[ERROR] urls[2] = file:/home/data/m2/repository/org/codehaus/mojo/keytool-api-1.7/1.6/keytool-api-1.7-1.6.jar
[ERROR] urls[3] = file:/home/data/m2/repository/org/apache/maven/shared/maven-shared-utils/3.3.4/maven-shared-utils-3.3.4.jar
[ERROR] urls[4] = file:/home/data/m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar
[ERROR] urls[5] = file:/home/data/m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] 
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:keytool-maven-plugin:1.6:generateKeyPair (generate-cxfca-keypair) on project camel-quarkus-integration-test-cxf-soap-ws-security-server: Execution generate-cxfca-keypair of goal org.codehaus.mojo:keytool-maven-plugin:1.6:generateKeyPair failed: A required class was missing while executing org.codehaus.mojo:keytool-maven-plugin:1.6:generateKeyPair: org/codehaus/plexus/util/StringUtils
-----------------------------------------------------
realm =    plugin>org.codehaus.mojo:keytool-maven-plugin:1.6
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/data/m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.6/keytool-maven-plugin-1.6.jar
urls[1] = file:/home/data/m2/repository/org/codehaus/mojo/keytool-api/1.6/keytool-api-1.6.jar
urls[2] = file:/home/data/m2/repository/org/codehaus/mojo/keytool-api-1.7/1.6/keytool-api-1.7-1.6.jar
urls[3] = file:/home/data/m2/repository/org/apache/maven/shared/maven-shared-utils/3.3.4/maven-shared-utils-3.3.4.jar
urls[4] = file:/home/data/m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar
urls[5] = file:/home/data/m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:339)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:322)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:172)
        at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
        at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:160)
        at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:37)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:157)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:106)
        at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:190)
        at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:208)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate-cxfca-keypair of goal org.codehaus.mojo:keytool-maven-plugin:1.6:generateKeyPair failed: A required class was missing while executing org.codehaus.mojo:keytool-maven-plugin:1.6:generateKeyPair: org/codehaus/plexus/util/StringUtils
-----------------------------------------------------
realm =    plugin>org.codehaus.mojo:keytool-maven-plugin:1.6
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/data/m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.6/keytool-maven-plugin-1.6.jar
urls[1] = file:/home/data/m2/repository/org/codehaus/mojo/keytool-api/1.6/keytool-api-1.6.jar
urls[2] = file:/home/data/m2/repository/org/codehaus/mojo/keytool-api-1.7/1.6/keytool-api-1.7-1.6.jar
urls[3] = file:/home/data/m2/repository/org/apache/maven/shared/maven-shared-utils/3.3.4/maven-shared-utils-3.3.4.jar
urls[4] = file:/home/data/m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar
urls[5] = file:/home/data/m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:162)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:334)
        ... 15 common frames omitted
Caused by: org.apache.maven.plugin.PluginContainerException: A required class was missing while executing org.codehaus.mojo:keytool-maven-plugin:1.6:generateKeyPair: org/codehaus/plexus/util/StringUtils
-----------------------------------------------------
realm =    plugin>org.codehaus.mojo:keytool-maven-plugin:1.6
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/data/m2/repository/org/codehaus/mojo/keytool-maven-plugin/1.6/keytool-maven-plugin-1.6.jar
urls[1] = file:/home/data/m2/repository/org/codehaus/mojo/keytool-api/1.6/keytool-api-1.6.jar
urls[2] = file:/home/data/m2/repository/org/codehaus/mojo/keytool-api-1.7/1.6/keytool-api-1.7-1.6.jar
urls[3] = file:/home/data/m2/repository/org/apache/maven/shared/maven-shared-utils/3.3.4/maven-shared-utils-3.3.4.jar
urls[4] = file:/home/data/m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar
urls[5] = file:/home/data/m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:161)
        ... 16 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/codehaus/plexus/util/StringUtils
        at org.codehaus.mojo.keytool.AbstractKeyToolRequestWithKeyStoreParametersMojo.createKeytoolRequest(AbstractKeyToolRequestWithKeyStoreParametersMojo.java:110)
        at org.codehaus.mojo.keytool.AbstractKeyToolRequestWithKeyStoreAndAliasParametersMojo.createKeytoolRequest(AbstractKeyToolRequestWithKeyStoreAndAliasParametersMojo.java:61)
        at org.codehaus.mojo.keytool.GenerateKeyPairMojo.createKeytoolRequest(GenerateKeyPairMojo.java:169)
        at org.codehaus.mojo.keytool.GenerateKeyPairMojo.createKeytoolRequest(GenerateKeyPairMojo.java:38)
        at org.codehaus.mojo.keytool.AbstractKeyToolRequestMojo.execute(AbstractKeyToolRequestMojo.java:126)
        at org.codehaus.mojo.keytool.GenerateKeyPairMojo.execute(GenerateKeyPairMojo.java:162)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:141)
        ... 16 common frames omitted
```

Steps to reproduce: 

1. install mvnd 1.0.0-m1 from https://github.com/apache/maven-mvnd/releases/tag/1.0.0-m1

```
mvnd -v
mvnd 1.0.0-m1 linux-amd64 native client (7586cf2b0cdd3b57238fa70802affb7a4e6f602f)Terminal: org.jline.terminal.impl.PosixSysTerminal with pty org.jline.terminal.impl.jansi.linux.LinuxNativePty
Apache Maven 4.0.0-alpha-3 (2ccf57baa5191468f9911fe85fd99672ac3bacb9)
Maven home: /home/ppalaga/.sdkman/candidates/mvnd/1.0.0-m1/mvn
Java version: 11.0.17, vendor: Eclipse Adoptium, runtime: /home/ppalaga/.sdkman/candidates/java/11.0.17-tem
Default locale: en_IE, platform encoding: UTF-8
OS name: "linux", version: "6.0.5-100.fc35.x86_64", arch: "amd64", family: "unix"
```

2. Clone and build Camel Quarkus

```
git clone git@github.com:apache/camel-quarkus.git
cd camel-quarkus
git reset --hard aa499ab8fd1f73523fff2964363c77f256a85556

# this fails already
mvnd install -Dquickly 

# you may want to switch to integration-test-groups/cxf-soap/cxf-soap-ws-security-server folder to see the error a bit better
cd integration-test-groups/cxf-soap/cxf-soap-ws-security-server
mvnd install -e
```

**Comment by slachiewicz** [comment]
I've added missing dependency to this plugin in #57
